default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: foodBaby_development

test: &test
  <<: *default
  database: foodBaby_test

production:
  <<: *default
  database: foodBaby_production

cucumber:
  <<: *test
